function pscfitgui
% ** function pscfitgui
% Graphical user interface for fitting exponential functions to
% postsynaptic currents. Code for callbacks of uicontrols is in
% pscfitguifunc.m.

% -------------------------------------------------------------------------
% Version 2.2, May 2012
% (C) Harald Hentschke (University of Tübingen)
% -------------------------------------------------------------------------

labelscale('fontSz',8,'scaleFac',1.0,'lineW',.25,'markSz',6); 

% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%              standards for layout of uicontrols & axes
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% the idea:
% - major vertical and horizontal separators are defined
% - all elements (uicontrol, axis) are left-aligned to these separators
% - axes must be somewhat offset from the separators because of axis labels
% etc.
% standard dimension of edit fields
editw=.12;
edith=.035;
% standard dimensions of buttons
butt1x=.12;
butt1y=.045;
butt2x=.16;
butt2y=.10;

% elementary delta y given height of text fields and smaller buttons
dy=.038;
% standard text field width (at least as wide as big buttons)
textw=.18;
% standard offsets of elements from predefined horizontal
% and vertical separators (defined below) and figure borders 
stdXMarg=.01;
stdYMarg=.01;
% standard offsets of subplots from predefined horizontal
% and vertical separators
plotXMarg=.025;
plotYMarg=.025;

% width of left 'column' of figure containing parameter input uicontrols
leftBlockW=editw+textw;
% vertical separators and corresponding horizontal widths in ascending order:
% - left button/parameter column starts at stdXMarg
la0=stdXMarg;
% - editable uicontrols in left button/parameter column 
la1=la0+textw;
% - subplots adjacent to left button/parameter column (any column layout)
la2=la0+leftBlockW;
% width of right part of figure (right of the button/parameter column) 
% containing essentially the axes
rightBlockW=1-la2-stdXMarg;
% - second subplot in a 2-column layout 
la3=la2+rightBlockW/2;
% - second subplot in a 3-column layout 
la4=la2+rightBlockW/3;
% - third subplot in a 3-column layout 
la5=la2+rightBlockW*2/3;

% vertical alignment lines from top to bottom
ba1=.96;

% font sizes
fsz=9;
fsz_big=12;


% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                         buttons
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% if gui exists from previous session, delete it
tmph=findobj('name', 'PSC fit', 'type', 'figure');
if ~isempty(tmph)
  delete(tmph);
end

% the collection of routines associated with most button callbacks
funcH1=@pscfitguifunc;

% create GUI window
H0 = figure('Units','normalized', ...
   'Color',[.6 .6 .6], ...
   'Name','PSC fit', ...
   'NumberTitle','off', ...
   'Position',[0.005 0.05 0.99 0.9], ...
   'Tag','PSCFit',...
   'MenuBar','none',...
   'Toolbar','figure',...
   'DeleteFcn',{funcH1,{'done'}}...
);

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[stdXMarg ba1-1*butt1y butt1x butt1y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'style','pushbutton',...
  'String','read data', ...
  'ForegroundColor',[0.3 .3 1], ...  
  'TooltipString','',...
  'Tag','readDataBttn', ...
  'callback', {funcH1,{'readData'}});  

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[stdXMarg ba1-2*butt1y butt1x butt1y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'style','pushbutton',...
  'String','clear data', ...
  'TooltipString','',...
  'Tag','clearDataBttn', ...
  'callback', {funcH1,{'clearData'}});  

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[stdXMarg ba1-3*butt1y butt1x butt1y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'style','pushbutton',...
  'String','average cutouts', ...
  'TooltipString','',...
  'Tag','avCutoutBttn', ...
  'callback', {funcH1,{'averageCutout'}});  

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[stdXMarg ba1-4*butt1y butt1x butt1y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'style','pushbutton',...
  'String','read params', ...
  'TooltipString','',...
  'Tag','readParBttn', ...
  'callback', {funcH1,{'loadParametersFromFile'}});  

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[stdXMarg ba1-5*butt1y butt1x butt1y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'style','pushbutton',...
  'String','save params', ...
  'TooltipString','',...
  'Tag','saveParBttn', ...
  'callback', {funcH1,{'saveParameters2File'}});  

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[stdXMarg+butt1x ba1-1*butt1y butt1x butt1y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'style','pushbutton',...
  'String','prepare fit', ...
  'ForegroundColor',[0.1 .7 0.1], ...  
  'TooltipString','',...
  'Tag','prepFitBttn', ...
  'callback', {funcH1,{'prepareFit'}});  

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[stdXMarg+butt1x ba1-2*butt1y butt1x butt1y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'style','pushbutton',...
  'String','fit', ...
  'ForegroundColor',[0.1 .5 0.1], ...  
  'TooltipString','',...
  'Tag','FitBttn', ...
  'callback', {funcH1,{'fit'}});  

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[stdXMarg+butt1x ba1-3*butt1y butt1x butt1y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'style','pushbutton',...
  'String','save results', ...
  'ForegroundColor','m', ...  
  'TooltipString','',...
  'Tag','saveResBttn', ...
  'callback', {funcH1,{'deleteEvents','saveResults'}});  

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[stdXMarg+butt1x ba1-4*butt1y butt1x butt1y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'style','pushbutton',...
  'String','DONE', ...
  'TooltipString','And now for something completely different...',...
  'ListboxTop',0, ...
  'Tag','doneBttn', ...
  'callback', {funcH1,{'done'}});  


% *********************   IMPORTANT    ************************************
% 1) All uicontrols MUST have a unique tag: first, in pscfitguifunc,
% uicontrols will be looked for via guihandles.m, which requires tags.
% Second, the value of each uicontrol will be assigned to a variable the
% name of which is identical to the uicontrol's tag. More precisely, tag
% names correspond to field names of ap and wp, structs which govern the
% workings of pscfitguifunc. Therefore, exact spelling of the tags is
% critical.
% 2) Editable (=not read-only) uicontrols must also have a callback routine
% that fetches the values entered and sets fields af ap or wp accordingly
% so that the choices are enabled instantaneously
% ************************************************************************

% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                          data treatment parameters
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tmpYOffs= -8*dy;
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-0*dy leftBlockW edith], ...
  'FontSize',fsz, ...
  'FontWeight','bold', ...
  'BackgroundColor',[0.9 0.9 0.9], ...
  'Style','text', ...
  'String','~~~~~~~~~~ data treatment parameters ~~~~~~~~~~~~~~', ...
  'Tag','headline1');

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-1*dy  textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[.6 .6 .6], ...
  'Style','text', ...  
  'String','min. sampling freq. (Hz)', ...
  'Tag','text_minSampFreq');
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la1 ba1+tmpYOffs-1*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH1,{'readParametersFromGui'}},...
  'Tag','minSampFreq');

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-2*dy  textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[.6 .6 .6], ...
  'Style','text', ...  
  'String','cutout interval (ms)', ...
  'Tag','text_winEvtCutout');
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la1 ba1+tmpYOffs-2*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH1,{'readParametersFromGui'}},...
  'Tag','winEvtCutout');

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-3*dy  textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[.6 .6 .6], ...
  'Style','text', ...  
  'String','pretrigger dead time (ms)', ...
  'Tag','text_nDecayComponent');
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la1 ba1+tmpYOffs-3*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH1,{'readParametersFromGui'}},...  
  'Tag','preTrigDeadT');

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-4*dy  textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[.6 .6 .6], ...
  'Style','text', ...  
  'String','lowpass cutoff freq (Hz)', ...
  'Tag','text_loCFreq');
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la1 ba1+tmpYOffs-4*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH1,{'readParametersFromGui'}},...
  'Tag','loCFreq');

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-5*dy  textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[.6 .6 .6], ...
  'Style','text', ...  
  'String','smoothing: time span (ms)', ...
  'Tag','text_smoothTSpan');
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la1 ba1+tmpYOffs-5*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH1,{'readParametersFromGui'}},...
  'Tag','smoothTSpan');
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                          fit parameters
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tmpYOffs= -14*dy;
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-0*dy leftBlockW edith], ...
  'FontSize',fsz, ...
  'FontWeight','bold', ...
  'BackgroundColor',[0.9 0.9 0.9], ...
  'Style','text', ...
  'String','~~~~~~~~~~ fit parameters ~~~~~~~~~~~~~~', ...
  'Tag','headline2');

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-1*dy  textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[.6 .6 .6], ...
  'Style','text', ...  
  'String','number of decay comp.', ...
  'Tag','text_nDecayComponent');
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la1 ba1+tmpYOffs-1*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH1,{'readParametersFromGui'}},...  
  'Tag','nDecayComponent');

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-2*dy  textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[.6 .6 .6], ...
  'Style','text', ...  
  'String','base line interval (ms)', ...
  'Tag','text_xIntvBaseLine');
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la1 ba1+tmpYOffs-2*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH1,{'readParametersFromGui'}},...
  'Tag','xIntvBaseLine');

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-3*dy  textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[.6 .6 .6], ...
  'Style','text', ...  
  'String','peak search interval (ms)', ...
  'Tag','text_xIntvPeak');
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la1 ba1+tmpYOffs-3*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH1,{'readParametersFromGui'}},...
  'Tag','xIntvPeak');

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-4*dy  textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[.6 .6 .6], ...
  'Style','text', ...  
  'String','min. fit interval right border (ms)', ...
  'Tag','text_xIntvFitEndMin');
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la1 ba1+tmpYOffs-4*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH1,{'readParametersFromGui'}},...
  'Tag','xIntvFitEndMin');

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-5*dy  textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[.6 .6 .6], ...
  'Style','text', ...  
  'String','max. fit interval right border (ms)', ...
  'Tag','text_xIntvFitEndMax');
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la1 ba1+tmpYOffs-5*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH1,{'readParametersFromGui'}},...
  'Tag','xIntvFitEndMax');

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-6*dy  textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[.6 .6 .6], ...
  'Style','text', ...  
  'String','post-peak delay of fit interval (ms)', ...
  'Tag','text_postPeakFitDelay');
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la1 ba1+tmpYOffs-6*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'callback', {funcH1,{'readParametersFromGui'}},...
  'Tag','postPeakFitDelay');

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-7*dy  textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[.6 .6 .6], ...
  'Style','text', ...  
  'String','min. quality of fit for history', ...
  'Tag','text_minFitQuality');
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la1 ba1+tmpYOffs-7*dy editw edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'tooltipstring',['the minimal fit quality, expressed in terms of adjusted r square, ',...
  'which each PSC has to fulfil in order to contribute to PSC history-based adjustment of PSC waveform'],...
  'callback', {funcH1,{'readParametersFromGui'}},...
  'Tag','minFitQuality');

h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...   
  'HorizontalAlignment','left', ...
  'Position',[stdXMarg ba1+tmpYOffs-9*dy  textw edith], ...  
  'FontSize',fsz, ...
  'BackgroundColor',[.6 .6 .6], ...
  'Style','text', ...  
  'String','comments/notes', ...
  'Tag','text_parComment');
h1 = uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la1 ba1+tmpYOffs-10*dy editw 2*edith], ... 
  'FontSize',fsz, ...   
  'BackgroundColor',[1 1 1], ...
  'Style','edit', ...
  'visible', 'on', ...
  'max',3,...
  'min',1,...
  'TooltipString','Here is some space for notes on the parameters',...
  'callback', {funcH1,{'readParametersFromGui'}},...
  'Tag','parComment');


% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                           axes
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% - all cutouts
sp.cutout.axH=subplot('position',[la2+plotXMarg  0.5+plotYMarg  rightBlockW/3*2-plotXMarg  0.5-plotYMarg-stdYMarg]);
set(sp.cutout.axH,'tag','cutouts');
% callback: toggle linestyle of cutouts
set(sp.cutout.axH,'buttondownfcn',{funcH1,{'toggleCutoutLineStyle'}})

% - selected cutouts
sp.selectCutout.axH=subplot('position',[la5+plotXMarg  0.1+plotYMarg  rightBlockW/3-plotXMarg  .9-plotYMarg-stdYMarg]);
set(sp.selectCutout.axH,'tag','selectedCutouts');

% - scatter plot including popupmenu UIs for axis and operation mode
% selection as well as button for deletion of events
% *** note that in deviation to all other parameters the UIs must NOT have
% tags identical to field names of wp and or ap - their values will be
% accessed directly via their handles (sp.scatter(1). ...
sp.scatter(1).axH=subplot(...
  'position',[la4+plotXMarg  0.1+plotYMarg  rightBlockW/3-plotXMarg  0.4-plotYMarg-stdYMarg]);
% note the callback
set(sp.scatter(1).axH,'tag','scatter1','buttondownfcn',{funcH1,{'reactCursorScatter'}});

sp.scatter(1).yAxMenuH=uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la4-editw 0.5-stdYMarg-edith editw edith], ... 
  'FontSize',fsz, ...   
  'Fontweight','bold', ...
  'BackgroundColor',[1 1 1], ...
  'Style','popupmenu', ...
  'String','y axis selection', ...  
  'callback', {funcH1,{'plotScatter'}},...
  'Tag','scatter1_yAxMenu');

sp.scatter(1).xAxMenuH=uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la4+plotXMarg 0.1-dy-0*edith editw edith], ... 
  'FontSize',fsz, ...   
  'Fontweight','bold', ...
  'BackgroundColor',[1 1 1], ...
  'Style','popupmenu', ...
  'String','x axis selection', ...  
  'callback', {funcH1,{'plotScatter'}},...
  'Tag','scatter1_xAxMenu');

sp.scatter(1).cursorModeMenuH=uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...
  'Position', [la4-editw 0.5-stdYMarg-2*edith editw edith], ... 
  'FontSize',fsz, ...   
  'Fontweight','bold', ...
  'BackgroundColor',[1 1 1], ...
  'Style','popupmenu', ...
  'String',{'probe','delete'}, ...  
  'callback', {funcH1,{'setScatterCursorMode'}},...
  'visible','on',... 
  'Tag','scatter1_cursorModeMenu');

sp.scatter(1).actionButton=uicontrol('Parent',H0, ...
  'Units','normalized', ...
  'HorizontalAlignment','left', ...    
  'Position',[la4-editw 0.5-stdYMarg-4*edith butt1x butt1y], ...
  'FontSize',fsz_big, ...
  'Fontweight','bold',...
  'ForegroundColor',[.9 .2 .2], ...
  'style','pushbutton',...
  'String','delete events', ...
  'TooltipString','Pressing this button will remove all events tagged in delete mode. This action cannot be undone.',...
  'Tag','delEvBttn', ...
  'callback', {funcH1,{'deleteEvents'}});  

pscfitguifunc(H0,[],{'init'},'sp',sp);
% pscfitguifunc(H0,[],{'init','loadParametersFromFile'},'sp',sp);

